# ESPHome Beehive Monitoring Package
#
# Battery-powered ESP32 beehive monitor with:
# - INMP441 microphone for FFT-based audio analysis
# - NAU7802 ADC for 4x 50kg load cells (weight)
# - SHT40 temperature and humidity sensor
# - Deep sleep for power efficiency (5 minute intervals)
#
# Usage: Include this as a package in your device configuration.
# See README.md for setup instructions.

substitutions:
  # I2C bus ID (user must define the i2c bus externally)
  i2c_bus_id: i2c_bus
  # I2S pins for INMP441 microphone
  i2s_lrclk_pin: GPIO1
  i2s_bclk_pin: GPIO3
  i2s_din_pin: GPIO7
  # GPIO pin to prevent deep sleep when held high at boot
  prevent_sleep_pin: GPIO11
  # Weight calibration points (raw_value -> weight_kg)
  # Record raw values at known weights and update these
  weight_cal_raw_1: "-242624"
  weight_cal_kg_1: "0"
  weight_cal_raw_2: "-241661"
  weight_cal_kg_2: "1.081"
  weight_cal_raw_3: "-240884"
  weight_cal_kg_3: "2.493"
  weight_cal_raw_4: "-238628"
  weight_cal_kg_4: "3.574"

esphome:
  on_boot:
    priority: -100 # Run after all components initialised
    then:
      - if:
          condition:
            binary_sensor.is_on: prevent_sleep_pin
          then:
            - logger.log: "Prevent sleep pin is high - disabling deep sleep"
            - switch.turn_on: prevent_deep_sleep
      - script.execute: collect_and_sleep

external_components:
  - source: github://johnf/esphome-beehive
    components: [bee_audio]
    refresh: 0s

# Deep sleep configuration - 5 minute intervals
deep_sleep:
  id: deep_sleep_control
  run_duration: 30s # Max awake time before forced sleep
  sleep_duration: 5min

# Custom bee audio component (INMP441 microphone)
# Pins:
#   - LRCLK (WS): GPIO25
#   - BCLK (SCK): GPIO26
#   - DIN (SD):   GPIO33
#   - VDD:        3.3V
#   - GND:        GND
#   - L/R:        GND (left channel)
bee_audio:
  id: bee_monitor
  i2s_lrclk_pin: ${i2s_lrclk_pin}
  i2s_bclk_pin: ${i2s_bclk_pin}
  i2s_din_pin: ${i2s_din_pin}
  sample_rate: 8000
  fft_size: 2048
  update_interval: never

sensor:
  # Bee audio frequency bands (power in dB)
  - platform: bee_audio
    bee_audio_id: bee_monitor
    band_low_freq:
      name: "Bee Low Frequency (60-100Hz)"
      id: bee_low_freq
    band_baseline:
      name: "Bee Baseline Hum (100-200Hz)"
      id: bee_baseline
    band_worker:
      name: "Bee Worker Activity (180-260Hz)"
      id: bee_worker
    band_quacking:
      name: "Bee Queen Quacking (200-350Hz)"
      id: bee_quacking
    band_tooting:
      name: "Bee Queen Tooting (350-500Hz)"
      id: bee_tooting
    band_queenless_mid:
      name: "Bee Queenless Mid (478-677Hz)"
      id: bee_queenless_mid
    band_queenless_high:
      name: "Bee Queenless High (876-1080Hz)"
      id: bee_queenless_high
    dominant_frequency:
      name: "Bee Dominant Frequency"
      id: bee_dominant_freq
    sound_level_rms:
      name: "Bee Sound Level"
      id: bee_sound_level
    spectral_centroid:
      name: "Bee Spectral Centroid"
      id: bee_spectral_centroid

  # NAU7802 load cell ADC (hive weight)
  # Calibration: Adjust the calibrate_linear filter based on your load cells
  # 1. Record raw value with empty hive
  # 2. Record raw value with known weight
  # 3. Update the linear calibration
  - platform: nau7802
    i2c_id: ${i2c_bus_id}
    id: hive_weight
    name: "Hive Weight"
    gain: 128
    unit_of_measurement: "kg"
    accuracy_decimals: 2
    update_interval: never
    filters:
      - calibrate_linear:
          - ${weight_cal_raw_1} -> ${weight_cal_kg_1}
          - ${weight_cal_raw_2} -> ${weight_cal_kg_2}
          - ${weight_cal_raw_3} -> ${weight_cal_kg_3}
          - ${weight_cal_raw_4} -> ${weight_cal_kg_4}

  # SHT40 temperature and humidity
  - platform: sht4x
    i2c_id: ${i2c_bus_id}
    id: hive_climate
    update_interval: never
    temperature:
      name: "Hive Temperature"
      id: hive_temp
    humidity:
      name: "Hive Humidity"
      id: hive_humidity

# Battery voltage monitoring (optional)
# Connect battery through voltage divider to GPIO34
# - platform: adc
#   pin: GPIO34
#   name: 'Battery Voltage'
#   id: battery_voltage
#   attenuation: 11db
#   filters:
#     - multiply: 2.0  # Voltage divider ratio

binary_sensor:
  - platform: gpio
    pin:
      number: ${prevent_sleep_pin}
      mode:
        input: true
        pulldown: true
    name: "Prevent Sleep Pin"
    id: prevent_sleep_pin
    internal: true
  - platform: bee_audio
    bee_audio_id: bee_monitor
    queen_piping:
      name: "Queen Piping Detected"
      id: queen_piping

text_sensor:
  - platform: bee_audio
    bee_audio_id: bee_monitor
    hive_state:
      name: "Hive State"
      id: hive_state

switch:
  - platform: template
    name: "Prevent Deep Sleep"
    id: prevent_deep_sleep
    optimistic: true
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - deep_sleep.prevent: deep_sleep_control
    on_turn_off:
      - deep_sleep.allow: deep_sleep_control

script:
  - id: collect_and_sleep
    then:
      - logger.log: "Starting measurement cycle"
      - wait_until:
          condition:
            wifi.connected:
          timeout: 10s
      - component.update: bee_monitor
      - component.update: hive_weight
      - component.update: hive_climate
      - wait_until:
          condition:
            api.connected:
          timeout: 10s
      - delay: 300ms
      - if:
          condition:
            switch.is_on: prevent_deep_sleep
          then:
            - logger.log: "Deep sleep prevented - staying awake"
            - delay: 5min
            - script.execute: collect_and_sleep
          else:
            - logger.log: "BeeHive: Entering deep sleep"
            - deep_sleep.enter: deep_sleep_control
