# Approximation of Bambu A1 mini, 0.4 nozzle, "0.20mm Standard", PLA Basic, 4 walls, 35% infill
bed_shape = 0x0,180x0,180x180,0x180
max_print_height = 180
nozzle_diameter = 0.4
filament_diameter = 1.75
filament_density = 1.24
layer_height = 0.2
first_layer_height = 0.2
perimeters = 4
top_solid_layers = 5
bottom_solid_layers = 3
fill_density = 35%
fill_pattern = grid
top_fill_pattern = monotonic
bottom_fill_pattern = monotonic
extrusion_width = 0.42
external_perimeter_extrusion_width = 0.42
first_layer_extrusion_width = 0.5
max_volumetric_speed = 21
external_perimeter_speed = 200
perimeter_speed = 300
small_perimeter_speed = 50
infill_speed = 270
solid_infill_speed = 250
top_solid_infill_speed = 200
gap_fill_speed = 250
bridge_speed = 50
travel_speed = 700
first_layer_speed = 50
first_layer_speed_over_raft = 50
default_acceleration = 10000
perimeter_acceleration = 5000
external_perimeter_acceleration = 5000
infill_acceleration = 10000
solid_infill_acceleration = 7000
top_solid_infill_acceleration = 2000
bridge_acceleration = 5000
first_layer_acceleration = 500
travel_acceleration = 10000
machine_limits_usage = time_estimate_only
machine_max_acceleration_extruding = 10000
machine_max_acceleration_retracting = 5000
machine_max_acceleration_travel = 10000
machine_max_acceleration_x = 10000
machine_max_acceleration_y = 10000
machine_max_acceleration_z = 1500
machine_max_acceleration_e = 5000
machine_max_feedrate_x = 500
machine_max_feedrate_y = 500
machine_max_feedrate_z = 20
machine_max_feedrate_e = 30
machine_max_jerk_x = 9
machine_max_jerk_y = 9
machine_max_jerk_z = 3
machine_max_jerk_e = 3
retract_length = 0.8
retract_speed = 30
support_material = 0
brim_width = 0
skirts = 0
gcode_flavor = marlin2
